In [3]:
import numpy as np

In [4]:
np.__version__

'1.18.1'

In [5]:
mylist=[1,2,3]

In [6]:
myarray = np.array(mylist)

In [7]:
myarray

array([1, 2, 3])

In [8]:
type(myarray)

numpy.ndarray

In [9]:
mynestedlist = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
mymatrix = np.array(mynestedlist)

In [11]:
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.linspace(0,10,101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.random.rand(5,2)

array([[0.34609564, 0.68136592],
       [0.42636197, 0.65832187],
       [0.94140226, 0.91661923],
       [0.44557673, 0.33093141],
       [0.64728719, 0.15129821]])

In [19]:
np.random.randn(5,5)

array([[ 0.4520886 , -0.55222067, -0.05368588, -0.57479379,  0.85836319],
       [-0.17241106, -1.10130877, -2.04068588, -1.37668823,  2.47816383],
       [ 1.06368304,  1.5759858 , -0.39948294, -0.67517745, -1.19424963],
       [ 0.84914512, -0.22683322, -0.62682567, -0.6999117 ,  0.78055331],
       [ 0.31330994, -0.61332706, -1.44672345, -0.09426057, -0.95394578]])

In [21]:
np.random.randint(0,101,(5,5))

array([[14, 12, 70, 93, 98],
       [17, 80, 25, 53, 38],
       [46, 36, 72, 54, 16],
       [69,  0, 68, 76, 27],
       [96, 49,  3, 14, 79]])

In [26]:
np.random.seed(42)
np.random.randn(5,5)

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337],
       [-0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783],
       [-0.56228753, -1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819, -0.54438272]])

In [27]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [29]:
arr = np.arange(0,25)

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr = np.arange(0,24)

In [34]:
arr.reshape(5,5)

ValueError: cannot reshape array of size 24 into shape (5,5)

In [37]:
arr.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
arr.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [39]:
arr.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [40]:
ranarr = np.random.randint(0,101,10)

In [41]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [43]:
ranarr.max()

99

In [44]:
ranarr.min()

2

In [45]:
ranarr.argmax()

5

In [47]:
ranarr.dtype

dtype('int32')

In [48]:
arr.shape

(24,)

In [49]:
arr = arr.reshape(6,4)

In [50]:
arr.shape

(6, 4)